const CONFIG = {

  LANDING_HEADER_BUTTON_1_TITLE: '公众号干货大师',
  LANDING_HEADER_BUTTON_1_URL: 'https://ai.230235.xyz',

  LANDING_HEADER_BUTTON_2_TITLE: '作者博客',
  LANDING_HEADER_BUTTON_2_URL: 'https://blog.230235.xyz/',

  // 首页大图英雄板块
  LANDING_HERO_TITLE_1: '干货大师',
  LANDING_HERO_P_1: '公众号：干货大师！',
  LANDING_HERO_BUTTON_1_TEXT: '开始体验',
  LANDING_HERO_BUTTON_1_LINK: 'https://ai.230235.xyz',
  LANDING_HERO_BUTTON_2_TEXT: '了解更多',
  LANDING_HERO_BUTTON_2_LINK: 'https://blog.230235.xyz',
  LANDING_HERO_VIDEO_IMAGE: '/images/home.png',
  //   HERO_VIDEO_URL: '/videos/video.mp4',
  LANDING_HERO_VIDEO_IFRAME: '//player.bilibili.com/player.html?aid=913088616&bvid=BV1fM4y1L7Qi&cid=1187218697&page=1&&high_quality=1',
  LANDING_HERO_VIDEO_TIPS: 'Watch the full video (2 min)',

  // 特性介绍
  LANDING_FEATURES_HEADER_1: '探索的过程',
  LANDING_FEATURES_HEADER_1_P: "1",
  LANDING_FEATURES_HEADER_2: '2',
  LANDING_FEATURES_HEADER_2_P: '3',
  LANDING_FEATURES_CARD_1_TITLE: '4',
  LANDING_FEATURES_CARD_1_P: '5',
  LANDING_FEATURES_CARD_2_TITLE: '6',
  LANDING_FEATURES_CARD_2_P: '7',
  LANDING_FEATURES_CARD_3_TITLE: '8',
  LANDING_FEATURES_CARD_3_P: '9',

  // 特性介绍2
  LANDING_FEATURES_BLOCK_HEADER: '10',
  LANDING_FEATURES_BLOCK_P: '11',
  LANDING_FEATURES_BLOCK_1_TITLE: '12',
  LANDING_FEATURES_BLOCK_1_P: '13',
  LANDING_FEATURES_BLOCK_2_TITLE: '14',
  LANDING_FEATURES_BLOCK_2_P: '15',
  LANDING_FEATURES_BLOCK_3_TITLE: '16',
  LANDING_FEATURES_BLOCK_3_P: '17',
  LANDING_FEATURES_BLOCK_4_TITLE: '18',
  LANDING_FEATURES_BLOCK_4_P: '19',
  LANDING_FEATURES_BLOCK_5_TITLE: '20',
  LANDING_FEATURES_BLOCK_5_P: '21',
  LANDING_FEATURES_BLOCK_6_TITLE: '22',
  LANDING_FEATURES_BLOCK_6_P: '23',

  // 感言
  LANDING_TESTIMONIALS_HEADER: '24',
  LANDING_TESTIMONIALS_P: '25',

  LANDING_TESTIMONIALS_AVATAR: 'https://230235.xyz',
  LANDING_TESTIMONIALS_NICKNAME: 'Ryan_G',
  LANDING_TESTIMONIALS_ID: 'e',
  LANDING_TESTIMONIALS_SOCIAL_NAME: '11',
  LANDING_TESTIMONIALS_SOCIAL_URL: 'https://blog.230235.xyz/',
  LANDING_TESTIMONIALS_WORD: '“ 22 “',

  LANDING_POST_REDIRECT_ENABLE: process.env.NEXT_PUBLIC_POST_REDIRECT_ENABLE || false, // 是否开启文章地址重定向 ； 用于迁移旧网站域名
  LANDING_POST_REDIRECT_URL: process.env.NEXT_PUBLIC_POST_REDIRECT_URL || 'https://blog.230235.xyz', // 重定向网站地址

  LANDING_PRICING_TITLE: '价格表',
  LANDING_PRICING_P: 'NotionNext开源免费，此处仅演示订阅付费功能！请勿购买！',

  LANDING_PRICING_1_TITLE: '个人版',
  LANDING_PRICING_1_PRICE: '免费',
  LANDING_PRICING_1_CONTENT: '0',
  LANDING_PRICING_1_BUTTON: '开始体验',
  LANDING_PRICING_1_URL: 'https://blog.230235.xyz',

  LANDING_PRICING_2_TITLE: '捐赠版',
  LANDING_PRICING_2_PRICE: '$9.9/月',
  LANDING_PRICING_2_CONTENT: '项目源代码,部署教程,长期技术答疑,代码升级合并,内部社群',
  LANDING_PRICING_2_BUTTON: '立即购买',
  LANDING_PRICING_2_URL: 'https://blog.230235.xyz',

  LANDING_PRICING_3_TITLE: '企业版',
  LANDING_PRICING_3_PRICE: '$59/月',
  LANDING_PRICING_3_CONTENT: '项目源代码,部署教程,VIP技术咨询,代码升级合并,内部社群,定制功能开发,SEO优化',
  LANDING_PRICING_3_BUTTON: '立即购买',
  LANDING_PRICING_3_URL: 'https://blog.230235.xyz',

  LANDING_NEWSLETTER: process.env.NEXT_PUBLIC_THEME_LANDING_NEWSLETTER || false // 是否开启邮件订阅 请先配置mailchimp功能 https://docs.tangly1024.com/article/notion-next-mailchimp
}
export default CONFIG
